AgeOfTerritory/src/Entity/Message.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\MessageRepository")
 */
class Message
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $title;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $content;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\User", inversedBy="messages")
     * @ORM\JoinColumn(nullable=false)
     */
    private $author;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\User", inversedBy="messages")
     * @ORM\JoinColumn(nullable=false)
     */
    private $recipient;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $etat;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $createdDate;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\User", inversedBy="messageCible")
     */
    private $cible;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getContent(): ?string
    {
        return $this->content;
    }

    public function setContent(string $content): self
    {
        $this->content = $content;

        return $this;
    }

    public function getAuthor(): ?User
    {
        return $this->author;
    }

    public function setAuthor(?User $author): self
    {
        $this->author = $author;

        return $this;
    }

    public function getRecipient(): ?User
    {
        return $this->recipient;
    }

    public function setRecipient(?User $recipient): self
    {
        $this->recipient = $recipient;

        return $this;
    }


    public function getEtat()
    {
        return $this->etat;
    }

    public function setEtat($etat): void
    {
        $this->etat = $etat;
    }

    public function getCible(): ?User
    {
        return $this->cible;
    }

    public function setCible(?User $cible): self
    {
        $this->cible = $cible;

        return $this;
    }

    /**
     * @return mixed
     */
    public function getCreatedDate()
    {
        return $this->createdDate;
    }

    /**
     * @param mixed $createdDate
     */
    public function setCreatedDate($createdDate): void
    {
        $this->createdDate = $createdDate;
    }

    public function __toString()
    {
        return $this->title;
    }


}

AgeOfTerritory/src/Entity/User.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Component\Security\Core\User\UserInterface;

/**
 * @ORM\Entity(repositoryClass="App\Repository\UserRepository")
 * @UniqueEntity("email")
 */
class User implements UserInterface
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=50, nullable=true)
     */
    private $username;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     * @Assert\Email(
     *     message = "L'adresse mail {{ value }} n'est pas une adresse email valide.",
     * )
     */
    private $email;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\Length(min="8", minMessage="Votre mot de passe doit comporté au minimum 8 caractères")
     */
    private $password;

    /**
     * @Assert\EqualTo(propertyPath="password", message="Le mot de passe et la confirmation de sont pas identiques !")
     */
    private $confirm_password;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $recordDate;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $lastLoginTimestamp;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $status;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Evolution", inversedBy="users")
     */
    private $evolution;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Message", mappedBy="author")
     */
    private $messages;


    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Isle", mappedBy="user")
     */
    private $isles;

    /**
     * @ORM\Column(type="array", nullable=true)
     *
     */
    private $roles = [];

    /**
     * @ORM\OneToOne(targetEntity="App\Entity\Isle", inversedBy="userMainIsle", cascade={"persist", "remove"})
     */
    private $mainIsle;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Message", mappedBy="cible")
     */
    private $messageCible;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\TrainingUnit")
     */
    private $preferenceUnitSpy;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\TrainingMachine")
     */
    private $preferenceMachineSpy;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $NbPreferenceSpy;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $resetToken;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $lastLogoutTimestamp;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $nbUnreadMessage;


    public function __construct()
    {
        $this->messages = new ArrayCollection();
        $this->searchTechnologies = new ArrayCollection();
        $this->isles = new ArrayCollection();
        $this->mainIsle = new ArrayCollection();
        $this->messageCible = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }


    public function getUsername(): ?string
    {
        return $this->username;
    }

    public function setUsername(string $username): self
    {
        $this->username = $username;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    public function getPassword(): ?string
    {
        return $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * @return mixed
     */
    public function getConfirmPassword()
    {
        return $this->confirm_password;
    }


    public function setConfirmPassword($confirm_password): void
    {
        $this->confirm_password = $confirm_password;
    }


    public function getRecordDate(): ?\DateTimeInterface
    {
        return $this->recordDate;
    }

    public function setRecordDate(\DateTimeInterface $recordDate): self
    {
        $this->recordDate = $recordDate;

        return $this;
    }

    /**
     * @return mixed
     */
    public function getLastLoginTimestamp()
    {
        return $this->lastLoginTimestamp;
    }

    /**
     * @param mixed $lastLoginTimestamp
     */
    public function setLastLoginTimestamp($lastLoginTimestamp): void
    {
        $this->lastLoginTimestamp = $lastLoginTimestamp;
    }

    /**
     * @return mixed
     */
    public function getLastLogoutTimestamp()
    {
        return $this->lastLogoutTimestamp;
    }

    /**
     * @param mixed $lastLogoutTimestamp
     */
    public function setLastLogoutTimestamp($lastLogoutTimestamp): void
    {
        $this->lastLogoutTimestamp = $lastLogoutTimestamp;
    }





    /**
     * @return mixed
     */
    public function getStatus()
    {
        return $this->status;
    }

    /**
     * @param mixed $status
     */
    public function setStatus($status): void
    {
        $this->status = $status;
    }


    public function getEvolution(): ?Evolution
    {
        return $this->evolution;
    }

    public function setEvolution(?Evolution $evolution): self
    {
        $this->evolution = $evolution;

        return $this;
    }

    /**
     * @return Collection|Message[]
     */
    public function getMessages(): Collection
    {
        return $this->messages;
    }

    public function addMessage(Message $message): self
    {
        if (!$this->messages->contains($message)) {
            $this->messages[] = $message;
            $message->setAuthor($this);
        }

        return $this;
    }

    public function removeMessage(Message $message): self
    {
        if ($this->messages->contains($message)) {
            $this->messages->removeElement($message);
            // set the owning side to null (unless already changed)
            if ($message->getAuthor() === $this) {
                $message->setAuthor(null);
            }
        }

        return $this;
    }


    /**
     * @return Collection|Isle[]
     */
    public function getIsles(): Collection
    {
        return $this->isles;
    }

    public function addIsle(Isle $isle): self
    {
        if (!$this->isles->contains($isle)) {
            $this->isles[] = $isle;
            $isle->setUser($this);
        }

        return $this;
    }

    public function removeIsle(Isle $isle): self
    {
        if ($this->isles->contains($isle)) {
            $this->isles->removeElement($isle);
            // set the owning side to null (unless already changed)
            if ($isle->getUser() === $this) {
                $isle->setUser(null);
            }
        }

        return $this;
    }

    public function getRoles(): array
    {
        $roles = $this->roles;
        // tous les utilisateurs on le role user
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    public function eraseCredentials(){}

    public function getSalt(){}

    /**
     * @return mixed
     */
    public function getMainIsle()
    {
        return $this->mainIsle;
    }

    /**
     * @param mixed $mainIsle
     */
    public function setMainIsle($mainIsle): void
    {
        $this->mainIsle = $mainIsle;
    }



    public function __toString():String
    {
        return $this->username;
    }

    /**
     * @return Collection|Message[]
     */
    public function getMessageCible(): Collection
    {
        return $this->messageCible;
    }

    public function addMessageCible(Message $messageCible): self
    {
        if (!$this->messageCible->contains($messageCible)) {
            $this->messageCible[] = $messageCible;
            $messageCible->setCible($this);
        }

        return $this;
    }

    public function removeMessageCible(Message $messageCible): self
    {
        if ($this->messageCible->contains($messageCible)) {
            $this->messageCible->removeElement($messageCible);
            // set the owning side to null (unless already changed)
            if ($messageCible->getCible() === $this) {
                $messageCible->setCible(null);
            }
        }

        return $this;
    }

    public function getPreferenceUnitSpy(): ?TrainingUnit
    {
        return $this->preferenceUnitSpy;
    }

    public function setPreferenceUnitSpy(?TrainingUnit $preferenceUnitSpy): self
    {
        $this->preferenceUnitSpy = $preferenceUnitSpy;

        return $this;
    }

    public function getPreferenceMachineSpy(): ?TrainingMachine
    {
        return $this->preferenceMachineSpy;
    }

    public function setPreferenceMachineSpy(?TrainingMachine $preferenceMachineSpy): self
    {
        $this->preferenceMachineSpy = $preferenceMachineSpy;

        return $this;
    }

    public function getNbPreferenceSpy(): ?int
    {
        return $this->NbPreferenceSpy;
    }

    public function setNbPreferenceSpy(?int $NbPreferenceSpy): self
    {
        $this->NbPreferenceSpy = $NbPreferenceSpy;

        return $this;
    }

    public function getResetToken(): ?string
    {
        return $this->resetToken;
    }

    public function setResetToken(?string $resetToken): self
    {
        $this->resetToken = $resetToken;

        return $this;
    }

    public function getNbUnreadMessage(): ?int
    {
        return $this->nbUnreadMessage;
    }

    public function setNbUnreadMessage(?int $nbUnreadMessage): self
    {
        $this->nbUnreadMessage = $nbUnreadMessage;

        return $this;
    }


}

AgeOfTerritory/templates/game/message/message.html.twig
{% extends('game/base_game.html.twig') %}

{% block body %}

    <h1 class="titre">Message(s)</h1>
    <div class="table-responsive bg-demi-transparent">
        <table class="width90 m-auto table table-hover">
            <tr class="width90 m-auto flex-around">
                <th class="">Message</th>
                <th>Expediteur</th>
                <th>Recu le</th>
            </tr>
            {% for message in messages %}

                <tr class="width90 m-auto flex-around">
                    <td> <a href="{{ path('message_show', {id_message:message.id} ) }}">{{ message.title }}</a></td>
                    <td> {{ message.author.username }} </td>
                    <td> {{ message.createdDate|date("d/m/Y \\à H:i:s", "Europe/Paris") }} </td>
                </tr>

            {% endfor %}
        </table>
    </div>


{% endblock %}

AgeOfTerritory/templates/game/message/show_message.html.twig
{% extends 'game/base_game.html.twig' %}

{% block body %}
    <div class="container-message bg-demi-transparent">

        {% if message.title == "Rapport d'espionnage" %}

            <div class="rapportEspionnage">
                <h1>{{ message.title }}</h1>

                <p> Rapport d'espionnage de '{{ message.cible.mainIsle.name }}'
                    <a href="{{ path('game_map',
                        {'longitude':message.cible.mainIsle.longitude,
                            'latitude':message.cible.mainIsle.latitude} ) }}">

                        ({{ message.cible.mainIsle.longitude }}:
                        {{ message.cible.mainIsle.latitude }}:
                        {{ message.cible.mainIsle.position }})
                    </a>
                </p>

                <p>Cette île appartient à {{ message.cible.username }}</p>

                <h2> Batiments </h2>

                <table class="table table-hover">

                    {% set buildings = message.cible.mainIsle.buildBuildings %}

                    <tr>
                        <th> Bâtiment </th>
                        <th> level  </th>
                    </tr>

                    {%  for building in buildings %}
                        <tr>
                            <td> {{ building.building.name }} </td>
                            <td> {{ building.levelBuilding }} </td>
                        </tr>
                    {% endfor %}

                </table>
                <h2> Technologies </h2>

                <table class="table table-hover">

                    {% set technologies = message.cible.mainIsle.searchTechnologies %}

                    <tr>
                        <th> Technologie </th>
                        <th> level  </th>
                    </tr>

                    {%  for technology in technologies %}
                        <tr>
                            <td> {{ technology.technology.name }} </td>
                            <td> {{ technology.levelTechnology }} </td>
                        </tr>
                    {% endfor %}

                </table>

                <h2> Machines </h2>

                <table class="table table-hover">

                    {% set machines = message.cible.mainIsle.trainingMachines %}

                    <tr>
                        <th> Machine </th>
                        <th> Nombre  </th>
                    </tr>

                    {%  for machine in machines %}
                        <tr>
                            <td> {{ machine.machine.name }} </td>
                            <td> {{ machine.nombre }} </td>
                        </tr>
                    {% endfor %}

                </table>
                <h2> Unitées </h2>

                <table class="table table-hover">

                    {% set units = message.cible.mainIsle.trainingUnits %}

                    <tr>
                        <th> Unitée </th>
                        <th> Nombre  </th>
                    </tr>

                    {%  for unit in units %}
                        <tr>
                            <td> {{ unit.unit.name }} </td>
                            <td> {{ unit.nombre }} </td>
                        </tr>
                    {% endfor %}

                </table>

                <h2> Défenses </h2>

                <table class="table table-hover">

                    {% set defenses = message.cible.mainIsle.buildDefenses %}

                    <tr>
                        <th> Défense </th>
                        <th> Nombre  </th>
                    </tr>

                    {%  for defense in defenses %}
                        <tr>
                            <td> {{ defense.defense.name }} </td>
                            <td> {{ defense.nombre }} </td>
                        </tr>
                    {% endfor %}

                </table>

            </div>
        {% endif %}

        {% if message.title == "Alert: Espionnage de votre île !" %}

            <div class="alertEspionnage">
                <h1>Espionnage</h1>
                <p>Les systemes de défense de votre île nous ont signaler une intrusion sur votre territoire.</p>
                <p>Nous avons repéré {{ message.author.nbPreferenceSpy }}
                    {% if message.author.preferenceUnitSpy == null %}
                        {{ message.author.preferenceMachineSpy.name }}(s)
                    {% elseif message.author.preferenceMachineSpy == null %}
                        {{ message.author.preferenceUnitSpy.name }}(s)
                    {% endif %}
                </p>
                <p>On dirait qu'il ont espionner votre territoire.</p>
                <p>Les ennemis venaient de
                    <a href="{{ path('game_getCoordinate',
                        {'longitude':message.author.mainIsle.longitude,
                            'latitude':message.author.mainIsle.latitude} ) }}">

                        {{ message.author.mainIsle.longitude }}:
                        {{ message.author.mainIsle.latitude }}:
                        {{ message.author.mainIsle.position }}
                    </a>
                </p>
            </div>

        {% endif %}

        {% if message.title == "Merci pour votre inscription !" %}
            <div class="message-inscription">
                <h1>Merci pour votre inscription !</h1>
                <p>L'équipe d'Age Of Territory vous souhaite la bienvenue sur notre serveur.</p>
                <p>Si vous avez la moindre question ou si vous voyer un bug, nous vous remercions d'avance de nous contactez pour régler le problème.</p>
                <p>Nous vous souhaitons Bon jeu !</p>
            </div>
        {% endif %}

    </div>


{% endblock %}